[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Laverde97/phd-data-science-ai/blob/main/semesters/semester-01/machine-learning/notebooks/class-notes/02-clase-2026-09-01.ipynb)

## SEGUNDA CLASE DE MACHINE LEARNING


In [ ]:
for i in range(1,6,1):
  print(i)

1
2
3
4
5


In [ ]:
# Pares

for i in range(1,21,1):
  print(2*i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40


In [ ]:
import numpy as np

# Using np.arange for decimal steps
print('Iterating with decimal steps using np.arange:')
for i in np.arange(0.5, 5.5, 0.75):
  print(i)

Iterating with decimal steps using np.arange:
0.5
1.25
2.0
2.75
3.5
4.25
5.0


In [ ]:
# Using np.linspace for a specific number of decimal points within a range
print('\nGenerating a specific number of decimal points with np.linspace:')
for i in np.linspace(0, 1, 5): # Generates 5 points between 0 and 1 (inclusive)
  print(i)


Generating a specific number of decimal points with np.linspace:
0.0
0.25
0.5
0.75
1.0


Existe un tema que se llama la libreria que se llama porciones de códigos que ya existe> Numpy, number de python, es una libreria que maneja todos los temas de números. Normalmente los desarrollados de software utilizaron las siglas np. Un arreglo es numpy de números y estan organizados.

In [ ]:
import numpy as np
A= np.array([-1,2,7,4,5])
print(A)

[-1  2  7  4  5]


Un **`np.array`** (o arreglo de NumPy) es la estructura de datos fundamental en la librería NumPy. Es similar a una lista de Python, pero con algunas diferencias clave:

*   **Homogeneidad**: Todos los elementos en un `np.array` deben ser del mismo tipo de datos (por ejemplo, todos enteros, todos flotantes, etc.). Esto permite a NumPy optimizar las operaciones.
*   **Eficiencia**: Los arreglos de NumPy están implementados en C, lo que los hace mucho más eficientes en términos de rendimiento y uso de memoria para operaciones numéricas, especialmente con grandes volúmenes de datos, en comparación con las listas de Python.
*   **Funcionalidades matemáticas**: `np.array` viene con una gran cantidad de funciones matemáticas y operaciones vectorizadas que se pueden aplicar a todo el arreglo de manera eficiente, sin necesidad de bucles explícitos en Python.

**¿Para qué se usa?**

Se utiliza ampliamente en:
*   **Cálculo numérico**: Para realizar operaciones matemáticas complejas de forma rápida y eficiente.
*   **Análisis de datos**: Es la base de muchas otras librerías como Pandas, Scikit-learn, etc.
*   **Machine Learning**: Almacenar y manipular características de datos, pesos de modelos, etc.
*   **Procesamiento de imágenes y señales**: Representar datos multidimensionales.

En el código `A = np.array([-1, 2, 7, 4, 5])`, estás creando un arreglo de NumPy unidimensional con los números enteros -1, 2, 7, 4 y 5.

In [ ]:
A=np.array([(1,2,3,4,5), (2,4,6,8,10)])
print('Matriz A')
print(A)

print('Matriz B')
B=np.array([(2,4,3,4,7), (1,4,7,2,10)])
print(B)
C=A+B
print('Matriz C')
print(C)

Matriz A
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Matriz B
[[ 2  4  3  4  7]
 [ 1  4  7  2 10]]
Matriz C
[[ 3  6  6  8 12]
 [ 3  8 13 10 20]]


In [ ]:
print('Ejercicio clase')

D=np.array([(1,2,3,4,5), (2,4,6,8,10)])
print('Matriz D')
print(D)

print('Matriz E')
E=np.array([(2,4,3,4,7), (1,4,7,2,10)])
print(E)
F=D-E
print('Matriz F')
print(F)

Ejercicio clase
Matriz D
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Matriz E
[[ 2  4  3  4  7]
 [ 1  4  7  2 10]]
Matriz F
[[-1 -2  0  0 -2]
 [ 1  0 -1  6  0]]


In [ ]:
print('Ejercicio clase')

D=np.array([(1,2,3,4,5), (2,4,6,8,10)])
print('Matriz D')
print(D)

print('Matriz E')
E=np.array([(2,4,3,4,7), (1,4,7,2,10)])
print(E)
F=D*E
print('Matriz F')
print(F)

Ejercicio clase
Matriz D
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
Matriz E
[[ 2  4  3  4  7]
 [ 1  4  7  2 10]]
Matriz F
[[  2   8   9  16  35]
 [  2  16  42  16 100]]


## LISTA

Una **lista en Python** es una colección ordenada y mutable de elementos. Esto significa lo siguiente:

*   **Ordenada**: Los elementos tienen un orden definido, y ese orden no cambia a menos que se modifique explícitamente la lista. Puedes acceder a los elementos por su índice (posición).
*   **Mutable**: Puedes cambiar, añadir o eliminar elementos de la lista después de que ha sido creada. No es una estructura fija.
*   **Colección**: Puede contener cualquier tipo de datos de Python, incluso mezclados (enteros, flotantes, cadenas de texto, otras listas, etc.).

**¿Para qué sirve una lista?**

Las listas son extremadamente útiles y se utilizan para:

1.  **Almacenar colecciones de datos**: Cuando necesitas guardar múltiples ítems que están relacionados entre sí, como una lista de nombres de estudiantes (`lista1 = ['Maria', 'Sofia', 'Laura', 'Carmen']`), una serie de números, o una colección de objetos.
2.  **Iteración**: Son perfectas para recorrer sus elementos usando bucles `for`, como en el ejercicio que planteaste para mostrar todo el contenido de la lista.
3.  **Manipulación de datos**: Permiten realizar operaciones como añadir elementos (`append()`, `insert()`), eliminar (`remove()`, `pop()`), ordenar (`sort()`), invertir (`reverse()`), buscar (`index()`), y más.
4.  **Implementar otras estructuras de datos**: Se pueden usar como base para implementar pilas, colas, o matrices simples antes de recurrir a librerías más especializadas como NumPy.

In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen'];
print(lista1[0]);
print(lista1[1]);
print(lista1[2]);
print(lista1[3]);

Maria
Sofia
Laura
Carmen


In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen'];
print(lista1);

['Maria', 'Sofia', 'Laura', 'Carmen']


Realizar un programa que utilizce for para que me muestre todo el contenido de la lista.

In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen'];
print(len(lista1));

4


In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen','Pedro'];
for i in range(len(lista1)): # Corregido: Usar range(len(lista1)) para iterar sobre los índices válidos
  print(lista1[i]);


Maria
Sofia
Laura
Carmen
Pedro


## AGREGAR ELEMENTOS A LA LISTA

In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen','Pedro'];
lista1.append('Juan');
lista1.append('Carlos');

for i in range(len(lista1)): # Corregido: Usar range(len(lista1)) para iterar sobre los índices válidos
  print(lista1[i]);


Maria
Sofia
Laura
Carmen
Pedro
Juan
Carlos


In [ ]:
listae = []
print("Por favor, ingresa 5 elementos para la lista:")
for i in range(5):
  elemento = input(f"Elemento {i+1}: ")
  listae.append(elemento)

print("\nElementos actuales de la lista:")
print(listae)

nombre_a_buscar = input("\nIngresa un nombre para buscar en la lista: ")

if nombre_a_buscar in listae:
  print(f"'{nombre_a_buscar}' se encontró en la lista.")
  indice = listae.index(nombre_a_buscar)
  listae.pop(indice)
  print("Lista después de eliminar el elemento:")
  print(listae)
else:
  print(f"'{nombre_a_buscar}' no se encontró en la lista.")
  print("La lista permanece sin cambios:")
  print(listae)


## ELIMINAR ELEMENTOS A LA LISTA

In [ ]:
listae = []

listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))

print(listae)

nombre = input("Digite el nombre que desea buscar: ")

if nombre in listae:
    indice = listae.index(nombre)
    listae.pop(indice)
    print("Lista nueva:", listae)
else:
    print("El nombre no está en la lista")

Digite un nombre: Juan
Digite un nombre: Luisa
Digite un nombre: Carlos
Digite un nombre: Juana
Digite un nombre: Sandra
['Juan', 'Luisa', 'Carlos', 'Juana', 'Sandra']
Digite el nombre que desea buscar: Carla
El nombre no está en la lista


In [ ]:
lista1= ['Maria', 'Sofia', 'Laura', 'Carmen','Pedro'];
lista1.append('Juan');
lista1.append('Carlos');
lista1.pop(1);

for i in range(len(lista1)): # Corregido: Usar range(len(lista1)) para iterar sobre los índices válidos
  print(lista1[i]);


Maria
Laura
Carmen
Pedro
Juan
Carlos


Construya un programa en python, que permita agregar 5 elementos a una lista (USE APPEND) llamada listae. Luego imprima los elementos de la lista.  Luego pregunte por un nombre para saber si esta o no en la lista. Si el nombre llega a estar en la lista, por favor eliminelo utilizando el iindice y la función pop. Luego muestre la lista sin el elemento eliminado.

In [ ]:
listae = [];
print("Por favor, ingresa 5 usuarios para la lista:");
for i in range(5):
  usuario = input(f"Usuario {i+1}: ");
  listae.append(usuario);

print("\nUsuarios actuales de la lista:");
print(listae);

Por favor, ingresa 5 usuarios para la lista:
Usuario 1: Juana
Usuario 2: Carla
Usuario 3: Juan
Usuario 4: Carlos
Usuario 5: Andres

Usuarios actuales de la lista:
['Juana', 'Carla', 'Juan', 'Carlos', 'Andres']


In [ ]:

listae = [] # Crear una lista vacía

#  Pedir LOS nombre y agregarlo a la lista
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))
listae.append(input("Digite un nombre: "))

# Mostrar todos los elementos de la lista
print(listae)

# Pedir el nombre que queremos buscar
nombre = input("Digite el nombre que desea buscar: ")

# Preguntar si el nombre está dentro de la lista
if nombre in listae:

    # Buscar la posición del nombre
    indice = listae.index(nombre)

    # Eliminar el nombre utilizando su posición
    listae.pop(indice)

    # Mostrar la lista después de eliminar el nombre
    print("Lista nueva:", listae)

# Si el nombre no está en la lista
else:

    # Mostrar este mensaje
    print("El nombre no está en la lista")

Digite un nombre: Juan 
Digite un nombre: Maria
Digite un nombre: Carla
Digite un nombre: Tomas
Digite un nombre: Maria
['Juan ', 'Maria', 'Carla', 'Tomas', 'Maria']
Digite el nombre que desea buscar: Maria
Lista nueva: ['Juan ', 'Carla', 'Tomas', 'Maria']


In [ ]:
listae=[];
indice=0;
flag=0;
tamaño=int(input('Digite el tamaño de la lista: '));
for i in range(tamaño):
  nombre=input('Digite el nombre');
  listae.append(nombre);

print(listae);
buscado=input('Digite el nombre a buscar');
for i in range(len(listae)):
   if buscado == listae[i]:
      indice=i;
      print('Si está en la lista')
      flag=1;
      break;
if flag == 0:
  print('El nombre no está en la lista');
else:
   listae.pop(indice);
print(listae);


Digite el tamaño de la lista: 4
Digite el nombreJuan
Digite el nombreMaria
Digite el nombreEmily
Digite el nombreCarla
['Juan', 'Maria', 'Emily', 'Carla']
Digite el nombre a buscarCarla
Si está en la lista
['Juan', 'Maria', 'Emily']


Por favor construya un ingreso a un sitio, debe decir si logró o no ingresar al sitio para eso usted debe tener un Password sencillo. Mientras no tenga el password debe mostrar un mensaje diciendo, no es el password correcto; hasta que no tenga el password correcto no lo deja ingresar al sitio.

In [ ]:
password = "1234"

intentos = 0

while intentos < 3:

    clave = input("Digite el password númerico: ")

    if clave == password:
        print("Logró ingresar al sitio")
        break
    else:
        print("No es el password correcto")
        intentos = intentos + 1

if intentos == 3:
    print("No logró ingresar al sitio, por favor comuniquese con el administrador")

Digite el password númerico: 2
No es el password correcto
Digite el password númerico: 3
No es el password correcto
Digite el password númerico: 5
No es el password correcto
No logró ingresar al sitio, por favor comuniquese con el administrador
